included:
  - TooSenior

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData

disabled_rules:
  - attributes
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - ibinspectable_in_extension
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

analyzer_rules:
  - unused_import
  - unused_declaration

# Rule configurations
trailing_newline: error
trailing_whitespace: error

line_length:
  warning: 120
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 8

cyclomatic_complexity:
  error: 10

file_length:
  warning: 400

identifier_name:
  min_length:
    error: 2
  max_length:
    error: 50
  excluded:
    - id
    - url
    - URL

type_name:
  min_length:
    error: 3
  max_length:
    warning: 50

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

multiline_parameters:
  allows_single_line: true

custom_rules:
  prefer_private:
    name: "Prefer private over fileprivate"
    regex: "fileprivate"
    message: "Prefer private over fileprivate unless you need to access from extensions in the same file"
    severity: warning
