name: TooSenior
options:
  bundleIdPrefix: com.vladyslav-krut
  createIntermediateGroups: true
  defaultConfig: Debug
  deploymentTarget:
    iOS: "17.0"

configs:
  Debug: debug
  Release: release

targets:
  TooSenior:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    
    sources:
      - path: TooSenior
        excludes:
          - "**/*.xcodeproj"
    
    resources:
      - TooSenior/Resources/Assets.xcassets
      - TooSenior/Resources/Base.lproj/LaunchScreen.storyboard
    
    info:
      path: TooSenior/Resources/Info.plist
    
    dependencies:
      - package: TooFoundation
      - package: OnboardingUI
    
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vladyslav-krut.TooSenior
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic

packages:
  TooFoundation:
    path: Modules/TooFoundation
  OnboardingUI:
    path: Modules/OnboardingUI

schemes:
  TooSenior:
    build:
      targets:
        TooSenior: all
    run:
      config: Debug